/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stdio.h"

int main(){
	int *p =  0x4002014;
	*p &=0; //*p = 0
	*p |= 0<<30;
	*(p+14)|=1<<15;
	for(int i=0;i<50;){

	}

}
