/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "driver_gpio_kck.h"
#include "stm32F103C6XX.h"
#include "stm32f103c6spi.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>


uint8_t sendorreceive= 0x30;
uint8_t readytosend= 0x31;
uint8_t sended =0x32;
uint8_t readytoreceive= 0x33;
uint8_t received =0x34;
void delay(int c){
	for (int i=0;i<c;i++);
}

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define GPIOX GPIOA

void afioinit(){


	AFIO_CLK_EN();
	PORTB_CLK_EN();
	PORTA_CLK_EN();
	//SPI1_CLK_EN();



uint32_t *p= (uint32_t*)0x40010004;
   *p |= 1<<0;

   //GPIO_CONFIG(8, GPIO_MODE_PULLUP, GPIOB);
   //GPIO_CONFIG(9,GPIO_MODE_PULLUP , GPIOB);
   GPIO_CONFIG(15, GPIO_GP_OP, GPIOA);
   GPIO_CONFIG(3, GPIO_AF_PP, GPIOB);
   GPIO_CONFIG(4, GPIO_AF_PP, GPIOB);
   GPIO_CONFIG(5, GPIO_AF_PP, GPIOB);


}



int main(void)
{
char   a[15]="dog";
char c='1';
uint8_t h=3;
uint8_t d=0;
uint8_t du;
afioinit();
spi_init();
spi_ssoe(1);


//spi_ssi(1);
//GPIO_writetooutputpin(15, 0, GPIOA);
while(1){
	//ack();

	//spi_send(&d, 1);
	spi_en(1);
	spi_send(&h, 1);
	spi_send(&d, 1);
	spi_receive(&du, 1);
	spi_en(0);



	//stop();


}



}
